export const ROUTES = {
  LOGIN: "/login",
  CARRERA: "/carrera",
  ADMISION: "/admision",
  CONTACTO: "/contacto",

  //estudiante
  ESTUDIANTE: "/estudiante",
  DASHBOARD: "/estudiante/dashboard",
  MATERIA: "/estudiante/materia",
  MATERIADETALLE: "/estudiante/materiadetalle/:id",
  PROYECTO: "/estudiante/proyecto",
  COLABORACION: "/estudiante/colaboracion",
  COLABORACIONDETALLE: "/estudiante/colaboraciones/:id",
  NOTIFICACION: "/estudiante/notificacion",
  TAREAPENDIENTE: "/estudiante/tareapendiente",
  PIZARRA: "/estudiante/pizarra",
  EXCALIDRAW: "/estudiante/excalidraw",
  CALENDARIOU: "/estudiante/calendario",

  //admin
  ADMIN: "/admin",
  DASHBOARDADMIN: "/admin/dashboard",
  GENERAL: "/admin/general",
  ADMINISTRADORES: "/admin/administradores",
  DIRECTORCARRERA: "/admin/directorCarrera",
  DOCENTE: "/admin/docente",
  USUARIO: "/admin/usuario",
  INSTITUCIONES: "/admin/instituciones",
  PERIODOS: "/admin/periodosAcademicos",
  FACULTAD: "/admin/facultad",
  CARRERAS: "/admin/carreras",
  SEMESTRE: "/admin/semestre",
  MATERIAS: "/admin/materias",
  CLASESPARALELOS: "/admin/clasesParalelos",
  HORARIO: "/admin/horario",
  INSCRIPCIONES: "/admin/inscripciones",
  PROYECTOS_ADMIN: "/admin/proyectos",
  EQUIPOS_ADMIN: "/admin/equipos",
  HITOS_ADMIN: "/admin/hitos",
  ENTREGAS_ADMIN: "/admin/entregas",
  REVISIONES_ADMIN: "/admin/revisiones",
  PLAGIOS: "/admin/plagiosIA",
  GITHUB: "/admin/repositoriosGithub",
  FERIAS: "/admin/ferias",
  FERIACATEGORIAS: "/admin/ferias/categorias",
  FERIAEQUIPOS: "/admin/ferias/equipos",
  FERIAJURADOS: "/admin/ferias/jurados",
  FERIAEVALUACIONES: "/admin/ferias/evaluaciones",
  REPORTEAVANCESEMESTRE: "/admin/reportes/avanceSemestre",
  REPORTEDOCENTES: "/admin/reportes/docentes",
  REPORTETOPPROYECTOS: "/admin/reportes/proyectosDestacados",
  REPORTEPLAGIO: "/admin/reportes/plagio",
  REPORTEEXPORTAR: "/admin/reportes/exportar",
  ROLES: "/admin/roles",
  PARAMETROS: "/admin/parametros",
  PERIODOACTIVO: "/admin/periodoActivo",

  //Vista usuario
  PRINCIPAL: "/",
  HOME: "/home",
  CARACTERISTICAS: "/caracteristicas",
  PLATAFORMAS: "/plataformas",
  CENTROAYUDA: "/centroAyuda",
  CONTACTOS: "/contactos",

  //Docente
  DOCENTES: "/docente",
  DASHBOARDDOCENTE: "/docente/dashboard",
  MISMATERIAS: "/docente/materias",
  ENTREGAS: "/docente/entregas",
  REVISION: "/docente/revision",
  RUBRICAS: "/docente/rubricas",
  CALENDARIODOC: "/docente/calendario",
  EVENTOS: "/docente/eventos",
  TAREAS: "/docente/tareas",
  NOTIFICACIONESDOC: "/docente/notificaciones",
  PLAGIO: "/docente/plagio",
  COLABORACIONES: "/docente/colaboracion",
  HORARIODOC: "/docente/horario",
  RECURSOS: "/docente/recursos",
  PIZARRADOC: "/docente/pizarra",
  EXCALIDRAWDOC: "/docente/excalidraw",

  //Director de carrera
  DIRECTOR: "/director",
  DASHBOARDDI: "/director/dashboard",
  REPORTESDI: "/director/reportes",
  MISMATERIASDI: "/director/materias",
  ENTREGASDI: "/director/entregas",
  REVISIONDI: "/director/revision",
  RUBRICASDI: "/director/rubricas",
  CALENDARIODI: "/director/calendario",
  EVENTOSDI: "/director/eventos",
  TAREASDI: "/director/tareas",
  NOTIFICACIONESDI: "/director/notificaciones",
  PLAGIODI: "/director/plagio",
  COLABORACIONESDI: "/director/colaboracion",
  HORARIODI: "/director/horario",
  RECURSODI: "/director/recursos",
  PIZARRADI: "/director/pizarra",
  EXCALIDRAWDI: "/director/excalidraw",
};
